### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by cellis** [madjam002/graphql-cache#1]
Hello! I came across this while looking for a simple AST caching solution for graphql. I noticed in the docs you use `print()` but I don't see any reference to that in the code. If it's not being maintained, why was work stopped on it? Just curious. It seems like a pretty solid library! Thanks!

**Comment by madjam002** [comment]
Thanks for getting in touch!

Unfortunately I'm not maintaining this repo anymore, I'll mark it as archived shortly. I just don't have a need for it anymore, and other libraries do caching much better now such as relay modern. That said I'm only getting started on a new GraphQL project so if Relay doesn't fit my needs then I might end up maintaining this library again, but it's unlikely :/

I too liked the idea of keeping it simple when it comes to caching GraphQL queries, but I just don't have the need or time to maintain this anymore, sorry :/

As for the `print()` call, that is part of the GraphQLJS API, so you should be able to import that from `graphql` 😄

**Comment by cellis** [comment]
It's interesting you mention relay modern, because that is exactly what I'm looking into using this library with. Relay-modern actually doesn't ship with a cache! Well, it does, but for a common use case it doesn't: multiple QueryRenderers with duplicate queries. I'm thinking of installing a cache like this in my relay-modern network layer, to prevent duplicate queries going to the graphql server. You can read more here: https://github.com/4Catalyzer/found-relay/issues/120

I'm unsure about a couple things however: 

1. 

Whether this AST is faster / worth the latency of the round trip. It seems like a diff/passThrough should only cost log(n) worst case so for the price of a bit of server side CPU you could get quite a bit of deduplication. 

2. 

How to handle pagination? I don't know the graphql spec inside out, but perhaps there is a way to hint to the network to just pass pagination calls straight through to the server? I'm interested in any insights you may have.

Thanks again for a great library!
